# Generated by Django 2.0.7 on 2019-10-20 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0003_auto_20191020_0544'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deletetweet',
            old_name='status_id',
            new_name='tweet_id',
        ),
    ]
