# Generated by Django 2.0.7 on 2019-10-20 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0004_auto_20191020_0546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deletetweet',
            name='tweet_id',
            field=models.IntegerField(),
        ),
    ]
